### ISSUE TITLE
Meta-issue: Windows

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/julia-buildkite#25]
Current status:

> Windows - These required a lot of work because our windows buildbot story has always been a :dumpster-fire: .  Previously, we had someone build windows VMs, used cygwin to install a bunch of compiler versions, and then whatever was installed was just what we got.  Updating the system meant potentially upgrading the compiler versions and breaking everything.  It was awful.  Also, the windows VMs often get wedged and must be restarted.  I have recently managed to streamline Windows VM creation via Packer, and figured out the proper KVM recipes to be able to run docker-on-windows-in-KVM on our amdci machines.  This means that we can build the system toolchains as docker images that get deployed onto the machines, providing reproducibility, and we can destroy the docker container after each build, which should provide a lot more reliability.  We will definitely need help creating the windows docker images and spearheading buildkite windows development, as I believe it’s mostly in powershell.

Next steps:

> We need to build windows docker images that contain the mingw32 build tools and windows platform SDK headers and whatnot necessary to build Julia.  We need to also build a set of powershell instructions to build and package Julia inside of that docker container, and then integrate the whole thing into buildkite.  This will involve some powershell scripting and some buildkite plugin development, I bet.

**Comment by inkydragon** [comment]
So, we want something like https://github.com/cirruslabs/docker-images-windows (windows + VisualStudio2022),
but we want w64-mingw32 not VS2022, right?

**Comment by inkydragon** [comment]
Some progress: https://github.com/inkydragon/msys2-mingw-w64
I've built a windows docker image (20H2 + MSYS2 + x86_64-w64-mingw32).
This is a POC, there are still many things todo.

**Comment by staticfloat** [comment]
This is great!

**Comment by staticfloat** [comment]
Okay, first some feedback:

* It appears that the images, as they are, can't be run on my windows buildbots.  The buildbots are running Windows Server 2022, and I think the issue is that by default, your images are built with the `20H2` image, which is somehow incompatible (I get the error message `The container operating system does not match the host operating system.`).  I can fix this by building the image locally, and manually setting `WIN_VERSION=ltsc2022`.

* It's not 100% necessary, but it would be nice to specifically install GCC 9, rather than just the latest available version of GCC (10 right now, it appears).  This would reduce variation across OSes in our build fleet, and also makes it less likely for us to rebuild the image and things suddenly break.

* When trying to build Julia, bootstrap fails with the following:
cd /c/Users/ContainerUser/Downloads/julia/usr/share/julia/src/base && /c/Users/ContainerUser/Downloads/julia/usr/bin/julia.exe -C "native" --output-ji /c/Users/ContainerUser/Downloads/julia/usr/lib/julia/corecompiler.ji.tmp --startup-file=no --warn-overwrite=yes -g0 -O0 compiler/compiler.jl
ERROR: Too few special library names specified, check LOADER_BUILD_DEP_LIBS and friends!
```

Do you get this error?

**Comment by inkydragon** [comment]
> can't be run on my windows buildbots.

Maybe you are using "process isolation mode". This is good and provides better performance.
With "Hyper-V isolation" mode, cross-version compatibility is improved, but performance is reduced.

ref: [Windows Container Version Compatibility | Microsoft Docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-11-21H2#windows-server-host-os-compatibility)

> it would be nice to specifically install GCC 9

Not quite sure how pacman selects the package version, for me it is GCC 12.
The documentation mentions a way to install a specific version manually:  [Package Management - MSYS2](https://www.msys2.org/docs/package-management/#installing-a-specific-version-of-a-package-or-a-stand-alone-packages).
Needs further exploration.

> Do you get this error?

I forgot that, you need some patches: https://github.com/JuliaLang/julia/pull/46140
