### ISSUE TITLE
Setting up CI on this repository (the `JuliaCI/julia-buildkite`) repository

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/julia-buildkite#28]
> We need to set up buildkite CI on the Julia-buildkite external repository so that we can start experimenting with different CI setups, then once we’re happy, we’ll point base Julia to that repository.  This will involve some system administration (setting the agents up on the build bots themselves) and some debugging of the buildkite webUI and whatnot.

**Comment by staticfloat** [comment]
I have enabled buildkite CI enough to get [a simple smoke test](https://github.com/JuliaCI/julia-buildkite/blob/a57756e2d6a3ea0114f444aafffc48591f89c014/.buildkite/pipeline.yaml) running.  Right now, the webui steps (the hidden steps that run at the beginning of every build, which are configured within the buildkite WebUI) just run `pipeline.yaml`, and that's how we'll keep it for now, until we're ready to start unlocking secrets and whatnot.

The first order of business is to figure out how to set up the bits on-disk in the exact same way as is done for base Julia.  My feeling is that we're probably going to want to [override the `checkout` hook](https://buildkite.com/docs/agent/v3/hooks#job-lifecycle-hooks) so that instead of it downloading this repository, it downloads the base julia repository.  From there, we should use the [`external-buildkite` plugin](https://github.com/JuliaCI/external-buildkite-buildkite-plugin) that Dilum has been working on to download the contents of _this_ repository in _exactly the same way_ as would be done for Base Julia.  The only difference is that I think we'll need to set up environment variables (that will be read by the `external-buildkite` plugin) to tell it to download the version that corresponds to the commit/PR that is currently being tested within this repository.
